ALTER TABLE recipes ALTER COLUMN ingridients TYPE VARCHAR(1500);
ALTER TABLE recipes ALTER COLUMN about TYPE VARCHAR;
ALTER TABLE recipes ALTER COLUMN instructions TYPE VARCHAR(2000);
ALTER TABLE recipes ALTER COLUMN title TYPE VARCHAR(50);
