ALTER TABLE recipes ALTER COLUMN ingridients TYPE VARCHAR(10000);
ALTER TABLE recipes ALTER COLUMN about TYPE VARCHAR(10000);
ALTER TABLE recipes ALTER COLUMN instructions TYPE VARCHAR(10000);
ALTER TABLE recipes ALTER COLUMN title TYPE VARCHAR(200);
